project:
  type: website
  output-dir: docs
  resources:
    - "*.html"
    - "*.csv"

website:
  title: "Breakout Strategy"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
