project:
  type: website
  output-dir: docs
  resources:
    - "*.html"
    - "*.csv"

website:
  title: "⚡ BREAKOUT STRATEGY"
  navbar:
    left:
      - href: index.qmd
        text: "🏠 Dashboard"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
